apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertContactPoint
metadata:
    name: edrfu9emozzswa
spec:
    disableResolveMessage: false
    name: email receiver
    settings:
        addresses: <example@email.com>
    type: email
    uid: edrfu9emozzswa
