{
 "title": "Merchants - Tx counts",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "merchantName",
    "label": "Merchant Name",
    "query": {}
   },
   {
    "name": "merchantId",
    "label": "Merchant ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Tx count per PSP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"merchantId\": \"$merchantId\",\r\n      \"pspId\": {\r\n        \"$ne\": null\r\n      },\r\n      \"createdAt\": {\r\n        \"$gte\": {\r\n          \"$date\": {\r\n            \"$numberLong\": \"$__from\"\r\n          }\r\n        },\r\n        \"$lte\": {\r\n          \"$date\": {\r\n            \"$numberLong\": \"$__to\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$pspId\",\r\n      \"transactionCount\": {\r\n        \"$sum\": 1\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"psps\",\r\n      \"localField\": \"_id\",\r\n      \"foreignField\": \"_id\",\r\n      \"as\": \"pspDetails\"\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$pspDetails\"\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"pspName\": \"$pspDetails.name\",\r\n      \"transactionCount\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"transactionCount\": -1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Tx count per mid",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"merchantId\": \"$merchantId\",\r\n      \"midId\": { \"$ne\": null },\r\n      \"createdAt\": {\r\n        \"$gte\": { \"$date\": { \"$numberLong\": \"$__from\" } },\r\n        \"$lte\": { \"$date\": { \"$numberLong\": \"$__to\" } }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$midId\",\r\n      \"transactionCount\": { \"$sum\": 1 }\r\n    }\r\n  },\r\n  {\r\n    \"$lookup\": {\r\n      \"from\": \"psp_mids\",\r\n      \"localField\": \"_id\",\r\n      \"foreignField\": \"_id\",\r\n      \"as\": \"pspDetails\"\r\n    }\r\n  },\r\n  {\r\n    \"$unwind\": \"$pspDetails\"\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"pspName\": \"$pspDetails.name\",\r\n      \"transactionCount\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": { \"transactionCount\": -1 }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Tx count per status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"merchantId\": \"$merchantId\",\r\n      \"createdAt\": {\r\n        \"$gt\": {\r\n          \"$date\": {\r\n            \"$numberLong\": \"$__from\"\r\n          }\r\n        },\r\n        \"$lt\": {\r\n          \"$date\": {\r\n            \"$numberLong\": \"$__to\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$status\",\r\n      \"Count\": {\r\n        \"$sum\": 1\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"Status\": \"$_id\",\r\n      \"Count\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"Count\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "$ per status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"merchantId\": \"$merchantId\",\r\n      \"createdAt\": {\r\n        \"$gt\": {\r\n          \"$date\": {\r\n            \"$numberLong\": \"$__from\"\r\n          }\r\n        },\r\n        \"$lt\": {\r\n          \"$date\": {\r\n            \"$numberLong\": \"$__to\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$status\",\r\n      \"totalAmount\": { \"$sum\": \"$fx.amount\" }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"Status\": \"$_id\",\r\n      \"totalAmount\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"totalAmount\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "AR per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"merchantId\": \"$merchantId\",\r\n      \"createdAt\": {\r\n        \"$gte\": { \"$date\": { \"$numberLong\": \"$__from\" } },\r\n        \"$lte\": { \"$date\": { \"$numberLong\": \"$__to\" } }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"$dateToString\": { \"format\": \"%Y-%m-%d\", \"date\": \"$createdAt\" }\r\n      },\r\n      \"txOthers\": {\r\n        \"$sum\": {\r\n          \"$cond\": [\r\n            { \"$and\": [{ \"$ne\": [\"$status\", \"COMPLETED\"] }, { \"$ne\": [\"$errorCategory\", 2] }] },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      },\r\n      \"txCompleted\": {\r\n        \"$sum\": { \"$cond\": [{ \"$eq\": [\"$status\", \"COMPLETED\"] }, 1, 0] }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"date\": { \"$dateFromString\": { \"dateString\": \"$_id\" } }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"date\": 1,\r\n      \"approvalRate\": {\r\n        \"$cond\": [\r\n          { \"$eq\": [{ \"$add\": [\"$txOthers\", \"$txCompleted\"] }, 0] },\r\n          100,\r\n          {\r\n            \"$round\": [\r\n              {\r\n                \"$multiply\": [\r\n                  {\r\n                    \"$divide\": [\"$txCompleted\", { \"$add\": [\"$txOthers\", \"$txCompleted\"] }]\r\n                  },\r\n                  100\r\n                ]\r\n              },\r\n              2\r\n            ]\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": { \"date\": 1 }\r\n  }\r\n]"
    }
   ]
  }
 ]
}