{
 "title": "All Merchants Transactions [5m]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FTH (SS) Tx / 5 Min",
   "type": "timeseries",
   "description": "FTH (SS) transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"a39ac315-0fb8-43f9-8f72-6dc4601bceaa\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "Mirata Tx / 5 Min",
   "type": "timeseries",
   "description": "Mirata transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"ac2a8d1b-85e4-4d05-8471-7e9af5634894\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "Softswiss Tx / 5 Min",
   "type": "timeseries",
   "description": "Softswiss transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"3a9e9723-90d0-454e-8bec-8c4f3a9d6403\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "TransactWorld Tx / 5 Min",
   "type": "timeseries",
   "description": "TransactWorld transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"c3e92779-2bcf-4682-95e9-ec25c3df155e\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "Pixturo Tx / 5 Min",
   "type": "timeseries",
   "description": "Pixturo transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"c40e0e89-52de-420e-ad2f-111e8a8dae99\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "VZTech Tx / 5 Min",
   "type": "timeseries",
   "description": "VZTech transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"608914a2-e309-4d10-9a2c-f90f9fb38e82\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "Digital Galaxy Tx / 5 Min",
   "type": "timeseries",
   "description": "Digital Galaxy transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"8b1c80a6-8fc7-426c-b4fb-5c79d3e76f77\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  },
  {
   "title": "Gumballpay Tx / 5 Min",
   "type": "timeseries",
   "description": "Gumballpay  transactions per 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[{\"$match\":{\"merchantId\":\"db3ef96b-aa74-41a3-b8d9-ff3ae2999253\",\"createdAt\":{\"$gt\":{\"$date\":{\"$numberLong\":\"$__from\"}},\"$lt\":{\"$date\":{\"$numberLong\":\"$__to\"}}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},300000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}]"
    }
   ]
  }
 ]
}