{
 "title": "System Overview - Kubernetes v2",
 "description": "Kubernetes Comprehensive display of resources:\n- Overall Resource Overview\n- Microservices Resource Details\n- Pod Resource Details \n- Network Bandwidth \n- Optimization metrics",
 "tags": [
  "kasha",
  "infra"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "K8S",
    "query": {
     "query": "label_values(kube_node_info,origin_prometheus)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\", container=~\"$Container\"},pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node Resource Overview：Selected Nodes:【$Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "Total Pod" },
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "Workload"
    },
    { "expr": "count by()(kube_node_info)", "legendFormat": "Total Nodes" }
   ]
  },
  {
   "title": "All Node Information Detail",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes)",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{origin_prometheus=~\"$origin_prometheus\"}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",origin_prometheus=~\"$origin_prometheus\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{origin_prometheus=~\"$origin_prometheus\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{origin_prometheus=~\"$origin_prometheus\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace：Network Overview（Associable nodes and namespaces）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$NameSpace\"}[2m])) * 8",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$NameSpace\"}[2m])) * 8",
     "legendFormat": "Send"
    }
   ]
  }
 ]
}