{
 "title": "[NOT USED] HTTP Status and Overview for Blackbox Exporter",
 "description": "Visualize HTTP data reported by blackbox exporter.  \r\nMade by Fabio Pardi - Agileos Consulting LTD \r\nYour Trusted Remote DBA\r\nwww.agileosconsulting.com ",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_duration_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number Of Monitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (up{job=\"blackbox-http\"})"
    }
   ]
  },
  {
   "title": "Uptime last 90 days for $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"$instance\"}[90d]) * 100 "
    }
   ]
  },
  {
   "title": "Average Response Time - $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((avg_over_time(probe_http_duration_seconds{instance=\"$instance\"}[24h])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Monitors Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success == 1)" }
   ]
  },
  {
   "title": "SSL Status on $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance SSL Certificate expiration in ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((probe_ssl_earliest_cert_expiry{instance=\"$instance\"}) - time()) / 60 / 60 / 24) "
    }
   ]
  },
  {
   "title": "HTTP status $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime Overview Last 24h - All Systems",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{}[24h]) * 100 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Detailed Overview for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Health Over Time - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(probe_success{instance=\"$instance\"}  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Response code - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count((probe_http_status_code{instance=\"$instance\"}  >= 200) AND (probe_http_status_code{instance=\"$instance\"}  <= 299))",
     "legendFormat": "Success 2xx"
    },
    {
     "expr": "count((probe_http_status_code{instance=\"$instance\"}  >= 300) AND (probe_http_status_code{instance=\"$instance\"}  <= 399))",
     "legendFormat": "Redirect 3xx"
    },
    {
     "expr": "count((probe_http_status_code{instance=\"$instance\"}  >= 400) AND (probe_http_status_code{instance=\"$instance\"}  <= 499))",
     "legendFormat": "Client Error 4xx"
    },
    {
     "expr": "count((probe_http_status_code{instance=\"$instance\"}  >= 500) AND (probe_http_status_code{instance=\"$instance\"}  <= 599))",
     "legendFormat": "Server Error 5xx"
    }
   ]
  },
  {
   "title": "Latency for $instance",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Breakdown - Latency for $instance",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(probe_http_duration_seconds{instance=\"$instance\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}