apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertNotificationTemplate
metadata:
    name: custom.services.alert.title
spec:
    name: custom.services.alert.title
    template: |-
        {{ define "custom.services.alert.title" }}
        {{ .CommonLabels.alertname }}
        {{ end }}
