apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertNotificationPolicy
metadata:
    name: global
spec:
    active_time_intervals: null
    group_by:
        - grafana_folder
        - alertname
    group_interval: 5m
    group_wait: 30s
    mute_time_intervals: null
    receiver: cyberpay-slack
    repeat_interval: 4h
    routes: null
