{
 "title": "Errors counting",
 "description": "The errors count manly from external API calls",
 "time": { "from": "now-10m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Payments service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Notifications service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Auth service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Api middleware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Cards service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Reports service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Notifications service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Mongo DB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Highisk PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Api gataway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Local payments adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Localpayments PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Ubiqpay adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Ubiqpay PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Payport adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Pagsmila adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Adyen PCI Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Bpwallet PCI Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Kasha PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Zro bank adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Ryvyl PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Stripe PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Rapyd PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Emerchpay PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Minoas adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Safetypay adapter service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Payaza PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Simulator PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Paymaxis PCI service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "A",
     "reducer": "sum",
     "type": "reduce"
    }
   ]
  },
  {
   "title": "Payments service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payments service errors",
     "type": "table",
     "description": "Visualize the count of the errors in payments service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:payments-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Api gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Api gateway errors",
     "type": "table",
     "description": "Visualize the count of the errors in api gateway",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:api-gateway AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Auth service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth service errors",
     "type": "table",
     "description": "Visualize the count of the errors in auth service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:auth-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Api middleware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Api middleware errors",
     "type": "table",
     "description": "Visualize the count of the errors in api middleware",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:api-middleware AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cards service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cards service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Cards service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:cards-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Reports service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reports service errors",
     "type": "table",
     "description": "Visualize the count of the errors in reports service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:reports-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Notifications service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications service errors",
     "type": "table",
     "description": "Visualize the count of the errors in notifications service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:notifications-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Highisk PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Highisk PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Highisk PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:highisk-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Bpwallet PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bpwallet PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Bpwaller PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:bpwallet-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Localpayments adapter service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Localpayments adapter service errors",
   "type": "table",
   "description": "Visualize the count of the errors in local payments adapter service",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "service.name:localpayments-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Localpayments PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Localpayments PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Localpayments PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:localpayments-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Ubiqpay adapter service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ubiqpay adapter service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Ubiqpay adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:ubiqpay-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Ubiqpay PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ubiqpay PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Ubiqpay PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:ubiqpay-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Adyen PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Adyen PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Adyen PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:adyen-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Safetypay adapter service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Safetypay adapter service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Safetypay adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:safetypay-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Kasha PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Highisk PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Kasha PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:kasha-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Zro bank adapter service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zro bank adapter service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Zro bank adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:zrobank-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Ryvyl PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ryvyl PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Rapyd PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:ryvyl-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Stripe PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stripe PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Stripe PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:stripe-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Rapyd PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rapyd PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Rapyd PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:rapyd-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Emerchantpay PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Emerchantpay PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Emerchantpay PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:emerchantpay-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Minoas adapter service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minoas adapter service errors",
     "type": "table",
     "description": "Visualize the count of the errors in minoas adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:minoas-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Paymaxis PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Paymaxis PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in paymaxis adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:paymaxis-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Payport adapter service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payport adapter service errors",
     "type": "table",
     "description": "Visualize the count of the errors in payport adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:payport-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Payaza PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payaza PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Payaza PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:payaza-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Pagsmile adapter service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pagsmile adapter service errors",
     "type": "table",
     "description": "Visualize the count of the errors in pagsmile adapter service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:pagsmile-adapter-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Simulator PCI service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simulator PCI service errors",
     "type": "table",
     "description": "Visualize the count of the errors in Rapyd PCI service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "service.name:simulator-pci-service AND service.environment:production AND (_index:traces-apm* OR _index:apm-* OR _index:logs-apm* OR _index:metrics-apm*) AND event.outcome: failure AND (http.response.status_code:[400 TO 599] OR (http.error_message:* OR http.error_name:* OR labels.http_error_message:* OR\nlabels.http_error_name:*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}