apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
    name: gke-prod-kasha.gke-prod-kasha
spec:
    folderUid: gke-prod-kasha
    interval: 300
    rules:
        - annotations:
            summary: Client's website is not ready after more than 15 minutes.
          condition: B
          data:
            - datasourceUid: metrics-gke-prod-kasha
              model:
                disableTextWrap: false
                editorMode: builder
                expr: kube_deployment_status_condition{namespace="deployments", status="false", condition="Available"} == 1
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: gke-prod-kasha
          for: 15m0s
          id: 1
          labels:
            owner: IT Operations
            priority: P1
          noDataState: OK
          orgID: 1
          ruleGroup: gke-prod-kasha
          title: ClientWebsiteNotReady
          uid: clientwebsitenotready-gke-prod-kasha
          updated: "2025-08-09T10:40:46.000Z"
        - annotations:
            summary: Backup Job {{ $labels.job_name }} has failed. Check the pod logs for details.
          condition: B
          data:
            - datasourceUid: metrics-gke-prod-kasha
              model:
                disableTextWrap: false
                editorMode: builder
                expr: increase(kube_job_status_failed{namespace="backups", job_name=~".*backup.*"}[24h]) > 0
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: gke-prod-kasha
          for: 5m0s
          id: 2
          labels:
            owner: IT Operations
            priority: P2
          noDataState: OK
          orgID: 1
          ruleGroup: gke-prod-kasha
          title: BackupFailed
          uid: backupfailed-gke-prod-kasha
          updated: "2025-08-09T10:40:46.000Z"
        - annotations:
            summary: RabbitMQ is down for the last 5 minutes.
          condition: B
          data:
            - datasourceUid: metrics-gke-prod-kasha
              model:
                datasource:
                    type: prometheus
                    uid: metrics-gke-prod-kasha
                disableTextWrap: false
                editorMode: builder
                expr: sum by(cluster, namespace, pod) (rabbitmq_build_info) < bool 1
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: gke-prod-kasha
          for: 5m0s
          id: 3
          labels:
            owner: IT Operations
            priority: P0
          noDataState: NoData
          orgID: 1
          ruleGroup: gke-prod-kasha
          title: RabbitmqDown
          uid: rabbitmqdown-gke-prod-kasha
          updated: "2025-08-09T10:40:46.000Z"
        - annotations:
            summary: Redis is down for the last 5 minutes.
          condition: B
          data:
            - datasourceUid: metrics-gke-prod-kasha
              model:
                datasource:
                    type: prometheus
                    uid: metrics-gke-prod-kasha
                disableTextWrap: false
                editorMode: code
                expr: redis_up == bool 0
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: gke-prod-kasha
          for: 5m0s
          id: 4
          labels:
            owner: IT Operations
            priority: P0
          noDataState: NoData
          orgID: 1
          ruleGroup: gke-prod-kasha
          title: RedisDown
          uid: redisdown-gke-prod-kasha
          updated: "2025-08-09T10:40:46.000Z"
        - annotations:
            summary: Minio is down for the last 5 minutes.
          condition: B
          data:
            - datasourceUid: metrics-gke-prod-kasha
              model:
                datasource:
                    type: prometheus
                    uid: metrics-gke-prod-kasha
                disableTextWrap: false
                editorMode: builder
                expr: sum by(cluster, namespace) (minio_cluster_health_status) == bool 0
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: gke-prod-kasha
          for: 5m0s
          id: 5
          labels:
            owner: IT Operations
            priority: P0
          noDataState: NoData
          orgID: 1
          ruleGroup: gke-prod-kasha
          title: MinioDown
          uid: miniodown-gke-prod-kasha
          updated: "2025-08-09T10:40:46.000Z"
        - annotations:
            summary: Kasha service is not ready after 5 minutes.
          condition: B
          data:
            - datasourceUid: metrics-gke-prod-kasha
              model:
                datasource:
                    type: prometheus
                    uid: metrics-gke-prod-kasha
                disableTextWrap: false
                editorMode: builder
                expr: kasha_service_health
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
              refId: B
              relativeTimeRange: {}
          execErrState: Error
          folderUID: gke-prod-kasha
          for: 5m0s
          id: 6
          labels:
            owner: Developement Team
            priority: P0
          noDataState: NoData
          orgID: 1
          ruleGroup: gke-prod-kasha
          title: KashaServiceNotReady
          uid: kashaservicenotready-gke-prod-kasha
          updated: "2025-08-09T10:40:46.000Z"
    title: gke-prod-kasha
