{
 "title": "Kubernetes Event Overview",
 "tags": [ "kasha" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "contains", "label": "Search events" }
  ]
 },
 "panels": [
  { "title": "Kubernetes Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (type) (count_over_time({source=\"kubernetes-events\"} | logfmt | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": " {source=\"kubernetes-events\"} |~ `(?i)$contains` | logfmt | __error__=`` | metadata_namespace=~`$namespace`"
    }
   ]
  },
  { "title": "Kubernetes Events - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TOP 10  Kubernetes Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(reason) (count_over_time({source=\"kubernetes-events\"} | logfmt | __error__=`` [$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Events by Reason",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (reason) (count_over_time({source=\"kubernetes-events\"} | logfmt | __error__=``  [$__interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Events by Namespace",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (namespace) (count_over_time({source=\"kubernetes-events\"} | logfmt | __error__=`` [$__interval]))",
     "legendFormat": "{{metadata_namespace}}"
    }
   ]
  },
  {
   "title": "Events by Source",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (sourcecomponent) (count_over_time({source=\"kubernetes-events\"}| logfmt | __error__=`` | metadata_namespace=~`$namespace` [$__interval]))",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "Events by Kind",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (kind) (count_over_time({source=\"kubernetes-events\"} | logfmt | __error__=`` [$__interval]))",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  }
 ]
}