{
 "title": "Backend Service Health Check",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kasha_service_health{exported_service=\"BOOKINGS_SERVICE\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Top 3 longest response Businesses API paths",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort_desc(topk(3, max_over_time({namespace=\"dev-lr\",container=\"istio-proxy\"}\r\n!~ `.ico|.svg|.css|.png|.txt|.js|.xml`\r\n| json\r\n| authority =~ `api-gateway.*`\r\n| unwrap duration\r\n| path =~ `/businesses/.*`\r\n| __error__=\"\" [3h]) by (path)))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Backend Services",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kasha_service_health{exported_service=~\"ECOM_ORDER_SERVICE|ECOM_PRICING_SERVICE|ECOM_PRODUCT_SERVICE\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Top Booking API paths",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort_desc(topk(1, max_over_time({namespace=\"dev-lr\",container=\"istio-proxy\"}\r\n!~ `.ico|.svg|.css|.png|.txt|.js|.xml`\r\n| json\r\n| authority =~ `api-gateway.*`\r\n| unwrap duration\r\n| path =~ `/auth/*`\r\n| __error__=\"\" [5m]) by (path)))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Database Services",
   "type": "stat",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kasha_service_health{exported_service=~\".+_DB\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}