{
 "title": "Tx counts",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "merchant",
    "query": {
     "query": "merchants.merchants.aggregate([\r\n  {\r\n    $project: {\r\n      value: \"$_id\",\r\n      name: 1\r\n    }\r\n  },\r\n  {\r\n    $sort: { name: 1 }\r\n  }\r\n])\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tx count per PSP",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"merchantId\":\"db3ef96b-aa74-41a3-b8d9-ff3ae2999253\",\"pspId\":{\"$ne\":null},\"createdAt\":{\"$gte\":{\"$date\":\"2024-06-14T06:44:17.254Z\"},\"$lte\":{\"$date\":\"2024-06-15T06:44:17.254Z\"}}}},{\"$group\":{\"_id\":\"$pspId\",\"transactionCount\":{\"$sum\":1}}},{\"$lookup\":{\"from\":\"psps\",\"localField\":\"_id\",\"foreignField\":\"_id\",\"as\":\"pspDetails\"}},{\"$unwind\":\"$pspDetails\"},{\"$project\":{\"_id\":0,\"pspName\":\"$pspDetails.name\",\"transactionCount\":1}},{\"$sort\":{\"transactionCount\":-1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      merchantId: \"$merchant\",\r\n      pspId: { $ne: null },\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: \"$pspId\",\r\n      transactionCount: { $sum: 1 }\r\n    }\r\n  },\r\n  {\r\n    $lookup: {\r\n      from: \"psps\",\r\n      localField: \"_id\",\r\n      foreignField: \"_id\",\r\n      as: \"pspDetails\"\r\n    }\r\n  },\r\n  {\r\n    $unwind: \"$pspDetails\"\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      pspName: \"$pspDetails.name\",\r\n      transactionCount: 1\r\n    }\r\n  },\r\n  {\r\n    $sort: { transactionCount: -1 }\r\n  }\r\n])\r\n"
    }
   ]
  },
  {
   "title": "Tx count per mid",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"merchantId\":\"db3ef96b-aa74-41a3-b8d9-ff3ae2999253\",\"midId\":{\"$ne\":null},\"createdAt\":{\"$gte\":{\"$date\":\"2024-06-14T06:44:17.254Z\"},\"$lte\":{\"$date\":\"2024-06-15T06:44:17.254Z\"}}}},{\"$group\":{\"_id\":\"$midId\",\"transactionCount\":{\"$sum\":1}}},{\"$lookup\":{\"from\":\"psp_mids\",\"localField\":\"_id\",\"foreignField\":\"_id\",\"as\":\"pspDetails\"}},{\"$unwind\":\"$pspDetails\"},{\"$project\":{\"_id\":0,\"pspName\":\"$pspDetails.name\",\"transactionCount\":1}},{\"$sort\":{\"transactionCount\":-1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      merchantId: \"$merchant\",\r\n      midId: { $ne: null },\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: \"$midId\",\r\n      transactionCount: { $sum: 1 }\r\n    }\r\n  },\r\n  {\r\n    $lookup: {\r\n      from: \"psp_mids\",\r\n      localField: \"_id\",\r\n      foreignField: \"_id\",\r\n      as: \"pspDetails\"\r\n    }\r\n  },\r\n  {\r\n    $unwind: \"$pspDetails\"\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      pspName: \"$pspDetails.name\",\r\n      transactionCount: 1\r\n    }\r\n  },\r\n  {\r\n    $sort: { transactionCount: -1 }\r\n  }\r\n])\r\n"
    }
   ]
  },
  {
   "title": "Tx count per status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"merchantId\":\"db3ef96b-aa74-41a3-b8d9-ff3ae2999253\",\"createdAt\":{\"$gte\":{\"$date\":\"2024-06-14T06:44:17.254Z\"},\"$lte\":{\"$date\":\"2024-06-15T06:44:17.254Z\"}}}},{\"$group\":{\"_id\":\"$status\",\"Count\":{\"$sum\":1}}},{\"$project\":{\"_id\":0,\"Status\":\"$_id\",\"Count\":1}},{\"$sort\":{\"Count\":1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      merchantId: \"$merchant\",\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: \"$status\",\r\n      Count: { $sum: 1 }\r\n    }\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      Status: \"$_id\",\r\n      Count: 1\r\n    }\r\n  },\r\n  {\r\n     $sort: { Count: 1 }\r\n  }\r\n])\r\n"
    }
   ]
  },
  {
   "title": "$ per status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"merchantId\":\"db3ef96b-aa74-41a3-b8d9-ff3ae2999253\",\"createdAt\":{\"$gte\":{\"$date\":\"2024-06-14T06:44:17.254Z\"},\"$lte\":{\"$date\":\"2024-06-15T06:44:17.254Z\"}}}},{\"$group\":{\"_id\":\"$status\",\"totalAmount\":{\"$sum\":\"$fx.amount\"}}},{\"$project\":{\"_id\":0,\"status\":\"$_id\",\"totalAmount\":1}},{\"$sort\":{\"totalAmount\":1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      merchantId: \"$merchant\",\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: \"$status\",\r\n      totalAmount: { $sum: \"$fx.amount\" },\r\n    }\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      status: \"$_id\",\r\n      totalAmount: 1,\r\n    }\r\n  },\r\n  {\r\n    $sort: { totalAmount: 1 }\r\n  }\r\n])\r\n"
    }
   ]
  },
  {
   "title": "AR per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"merchantId\":\"db3ef96b-aa74-41a3-b8d9-ff3ae2999253\",\"createdAt\":{\"$gte\":{\"$date\":\"2024-06-15T07:27:18.712Z\"},\"$lte\":{\"$date\":\"2024-06-15T19:27:18.712Z\"}}}},{\"$group\":{\"_id\":{\"$dateToString\":{\"format\":\"%Y-%m-%d\",\"date\":\"$createdAt\"}},\"txOthers\":{\"$sum\":{\"$cond\":[{\"$and\":[{\"$ne\":[\"$status\",\"COMPLETED\"]},{\"$ne\":[\"$errorCategory\",2]}]},1,0]}},\"txCompleted\":{\"$sum\":{\"$cond\":[{\"$eq\":[\"$status\",\"COMPLETED\"]},1,0]}}}},{\"$addFields\":{\"date\":{\"$dateFromString\":{\"dateString\":\"$_id\"}}}},{\"$project\":{\"_id\":0,\"date\":1,\"approvalRate\":{\"$cond\":[{\"$eq\":[{\"$add\":[\"$txOthers\",\"$txCompleted\"]},0]},100,{\"$round\":[{\"$multiply\":[{\"$divide\":[\"$txCompleted\",{\"$add\":[\"$txOthers\",\"$txCompleted\"]}]},100]},2]}]}}},{\"$sort\":{\"date\":1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      merchantId: \"$merchant\",\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: {\r\n        $dateToString: { format: \"%Y-%m-%d\", date: \"$createdAt\" }\r\n      },\r\n      txOthers: {\r\n        $sum: {\r\n          $cond: [\r\n            { $and: [{ $ne: ['$status', 'COMPLETED'] }, { $ne: ['$errorCategory', 2] }] },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      },\r\n      txCompleted: {\r\n        $sum: { $cond: [{ $eq: ['$status', 'COMPLETED'] }, 1, 0] }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $addFields: {\r\n      date: { $dateFromString: { dateString: \"$_id\" } }\r\n    }\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      date: 1,\r\n      approvalRate: {\r\n        $cond: [\r\n          { $eq: [{ $add: ['$txOthers', '$txCompleted'] }, 0] },\r\n          100,\r\n          {\r\n            $round: [\r\n              {\r\n                $multiply: [\r\n                  {\r\n                    $divide: ['$txCompleted', { $add: ['$txOthers', '$txCompleted'] }]\r\n                  },\r\n                  100\r\n                ]\r\n              },\r\n              2\r\n            ]\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $sort: { date: 1 }\r\n  }\r\n])\r\n"
    }
   ]
  }
 ]
}