{
 "title": "[Screen 1] - HTTP Health Check",
 "description": "Blackbox exporter HTTP dashboard",
 "tags": [ "kasha" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Probe Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success == 1)" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 1 },
   "targets": [
    { "expr": "probe_http_status_code" },
    {
     "expr": "probe_ssl_earliest_cert_expiry - time()"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry * 1000"
    },
    { "expr": "probe_duration_seconds" },
    { "expr": "probe_dns_lookup_time_seconds" },
    { "expr": "probe_success" },
    {
     "expr": "probe_tls_version_info{ version=~\".*.1\"}"
    },
    {
     "expr": "probe_tls_version_info{version=~\".*.2\"}"
    },
    {
     "expr": "probe_tls_version_info{version=~\".*.3\"}"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success== 0)" }
   ]
  },
  { "title": "HTTP Probe Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "System Uptime - Last 24h",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{}[24h]) * 100 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}