apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertNotificationPolicy
metadata:
    name: global
spec:
    active_time_intervals: null
    group_by:
        - grafana_folder
        - alertname
    mute_time_intervals: null
    receiver: grafana-default-email
    routes:
        - active_time_intervals: null
          group_by:
            - alertname
          mute_time_intervals: null
          object_matchers:
            - - alerts
              - =
              - kasha
          receiver: Kasha Microservices
          repeat_interval: 45m
          routes: null
        - active_time_intervals: null
          group_by: null
          mute_time_intervals: null
          object_matchers:
            - - notification
              - =
              - kasha-merchant
          routes: null
