{
 "title": "Transactions per minute",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Transactions per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"createdAt\": {\n        \"$gte\": {\n          \"$date\": {\n            \"$numberLong\": \"$__from\"\n          }\n        },\n        \"$lte\": {\n          \"$date\": {\n            \"$numberLong\": \"$__to\"\n          }\n        }\n      }\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": {\n        \"$toDate\": {\n          \"$subtract\": [\n            { \"$toLong\": \"$createdAt\" },\n            { \"$mod\": [{ \"$toLong\": \"$createdAt\" }, 60000] }\n          ]\n        }\n      },\n      \"count\": { \"$sum\": 1 }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 1,\n      \"count\": 1\n    }\n  },\n  {\n    \"$sort\": {\n      \"_id\": 1\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "AR per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "collection": "transactions",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"category\": \"PAYIN\",\n      \"status\": {\n        \"$nin\": [\n          \"CHARGEBACK\",\n          \"REFUNDED\"\n        ]\n      },\n      \"createdAt\": {\n        \"$gte\": {\n          \"$date\": {\n            \"$numberLong\": \"$__from\"\n          }\n        },\n        \"$lte\": {\n          \"$date\": {\n            \"$numberLong\": \"$__to\"\n          }\n        }\n      }\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": {\n        \"$dateToString\": {\n          \"format\": \"%Y-%m-%dT%H:%M\",\n          \"date\": \"$createdAt\"\n        }\n      },\n      \"txOthers\": {\n        \"$sum\": {\n          \"$cond\": [\n            {\n              \"$and\": [\n                {\n                  \"$ne\": [\n                    \"$status\",\n                    \"COMPLETED\"\n                  ]\n                },\n                {\n                  \"$ne\": [\n                    \"$errorCategory\",\n                    2\n                  ]\n                }\n              ]\n            },\n            1,\n            0\n          ]\n        }\n      },\n      \"txCompleted\": {\n        \"$sum\": {\n          \"$cond\": [\n            {\n              \"$eq\": [\n                \"$status\",\n                \"COMPLETED\"\n              ]\n            },\n            1,\n            0\n          ]\n        }\n      }\n    }\n  },\n  {\n    \"$addFields\": {\n      \"date\": {\n        \"$dateFromString\": {\n          \"dateString\": \"$_id\",\n          \"format\": \"%Y-%m-%dT%H:%M\"\n        }\n      }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"date\": 1,\n      \"approvalRate\": {\n        \"$cond\": [\n          {\n            \"$eq\": [\n              {\n                \"$add\": [\n                  \"$txOthers\",\n                  \"$txCompleted\"\n                ]\n              },\n              0\n            ]\n          },\n          100,\n          {\n            \"$round\": [\n              {\n                \"$multiply\": [\n                  {\n                    \"$divide\": [\n                      \"$txCompleted\",\n                      {\n                        \"$add\": [\n                          \"$txOthers\",\n                          \"$txCompleted\"\n                        ]\n                      }\n                    ]\n                  },\n                  100\n                ]\n              },\n              2\n            ]\n          }\n        ]\n      }\n    }\n  },\n  {\n    \"$sort\": {\n      \"date\": 1\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "Validation errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "collection": "transaction_attempts",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"createdAt\": {\n        \"$gte\": {\n          \"$date\": {\n            \"$numberLong\": \"$__from\"\n          }\n        },\n        \"$lte\": {\n          \"$date\": {\n            \"$numberLong\": \"$__to\"\n          }\n        }\n      }\n    }\n  },\n  {\n    \"$group\": {\n      \"_id\": {\n        \"$toDate\": {\n          \"$subtract\": [\n            { \"$toLong\": \"$createdAt\" },\n            { \"$mod\": [ { \"$toLong\": \"$createdAt\" }, 60000 ] }\n          ]\n        }\n      },\n      \"count\": { \"$sum\": 1 }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 1,\n      \"count\": 1\n    }\n  },\n  {\n    \"$sort\": { \"time\": 1 }\n  }\n]"
    }
   ]
  }
 ]
}