{
 "title": "Transactions per minute",
 "tags": [ "mongodb" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Transactions per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"createdAt\":{\"$gte\":{\"$date\":\"2025-01-15T23:31:48.195Z\"},\"$lte\":{\"$date\":\"2025-01-16T11:31:48.196Z\"}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},60000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: {\r\n        $toDate: {\r\n          $subtract: [\r\n            { $toLong: \"$createdAt\" },\r\n            { $mod: [{ $toLong: \"$createdAt\" }, 1000 * 60 * 1] }\r\n          ]\r\n        }\r\n      },\r\n      count: { $sum: 1 }\r\n    }\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 1,\r\n      count: 1,\r\n    }\r\n  },\r\n  {\r\n    $sort: { time: 1 }\r\n  }\r\n])\r\n"
    }
   ]
  },
  {
   "title": "AR per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "parsedQuery": "payments.transactions.aggregate([{\"$match\":{\"category\":\"PAYIN\",\"status\":{\"$nin\":[\"CHARGEBACK\",\"REFUNDED\"]},\"createdAt\":{\"$gte\":{\"$date\":\"2025-01-15T23:31:48.195Z\"},\"$lte\":{\"$date\":\"2025-01-16T11:31:48.196Z\"}}}},{\"$group\":{\"_id\":{\"$dateToString\":{\"format\":\"%Y-%m-%dT%H:%M\",\"date\":\"$createdAt\"}},\"txOthers\":{\"$sum\":{\"$cond\":[{\"$and\":[{\"$ne\":[\"$status\",\"COMPLETED\"]},{\"$ne\":[\"$errorCategory\",2]}]},1,0]}},\"txCompleted\":{\"$sum\":{\"$cond\":[{\"$eq\":[\"$status\",\"COMPLETED\"]},1,0]}}}},{\"$addFields\":{\"date\":{\"$dateFromString\":{\"dateString\":\"$_id\",\"format\":\"%Y-%m-%dT%H:%M\"}}}},{\"$project\":{\"_id\":0,\"date\":1,\"approvalRate\":{\"$cond\":[{\"$eq\":[{\"$add\":[\"$txOthers\",\"$txCompleted\"]},0]},100,{\"$round\":[{\"$multiply\":[{\"$divide\":[\"$txCompleted\",{\"$add\":[\"$txOthers\",\"$txCompleted\"]}]},100]},2]}]}}},{\"$sort\":{\"date\":1}}])\n",
     "query": "payments.transactions.aggregate([\r\n  {\r\n    $match: {\r\n      category: \"PAYIN\",\r\n      status: { $nin: [\"CHARGEBACK\", \"REFUNDED\"] },\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: {\r\n        $dateToString: { format: \"%Y-%m-%dT%H:%M\", date: \"$createdAt\" }\r\n      },\r\n      txOthers: {\r\n        $sum: {\r\n          $cond: [\r\n            { $and: [{ $ne: ['$status', 'COMPLETED'] }, { $ne: ['$errorCategory', 2] }] },\r\n            1,\r\n            0\r\n          ]\r\n        }\r\n      },\r\n      txCompleted: {\r\n        $sum: { $cond: [{ $eq: ['$status', 'COMPLETED'] }, 1, 0] }\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $addFields: {\r\n      date: { $dateFromString: { dateString: \"$_id\", format: \"%Y-%m-%dT%H:%M\" } }\r\n    }\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      date: 1,\r\n      approvalRate: {\r\n        $cond: [\r\n          { $eq: [{ $add: ['$txOthers', '$txCompleted'] }, 0] },\r\n          100,\r\n          {\r\n            $round: [\r\n              {\r\n                $multiply: [\r\n                  {\r\n                    $divide: ['$txCompleted', { $add: ['$txOthers', '$txCompleted'] }]\r\n                  },\r\n                  100\r\n                ]\r\n              },\r\n              2\r\n            ]\r\n          }\r\n        ]\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $sort: { date: 1 }\r\n  }\r\n])\r\n"
    }
   ]
  },
  {
   "title": "Validation errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "parsedQuery": "payments.transaction_attempts.aggregate([{\"$match\":{\"createdAt\":{\"$gte\":{\"$date\":\"2024-08-08T07:39:24.978Z\"},\"$lte\":{\"$date\":\"2024-08-09T07:39:24.978Z\"}}}},{\"$group\":{\"_id\":{\"$toDate\":{\"$subtract\":[{\"$toLong\":\"$createdAt\"},{\"$mod\":[{\"$toLong\":\"$createdAt\"},60000]}]}},\"count\":{\"$sum\":1}}},{\"$project\":{\"_id\":1,\"count\":1}},{\"$sort\":{\"time\":1}}])\n",
     "query": "payments.transaction_attempts.aggregate([\r\n  {\r\n    $match: {\r\n      createdAt: {\r\n        $gte: new ISODate($__from),\r\n        $lte: new ISODate($__to)\r\n      }\r\n    }\r\n  },\r\n  {\r\n    $group: {\r\n      _id: {\r\n        $toDate: {\r\n          $subtract: [\r\n            { $toLong: \"$createdAt\" },\r\n            { $mod: [{ $toLong: \"$createdAt\" }, 1000 * 60 * 1] }\r\n          ]\r\n        }\r\n      },\r\n      count: { $sum: 1 }\r\n    }\r\n  },\r\n  {\r\n    $project: {\r\n      _id: 1,\r\n      count: 1,\r\n    }\r\n  },\r\n  {\r\n    $sort: { time: 1 }\r\n  }\r\n])\r\n"
    }
   ]
  }
 ]
}